@startuml
sorter -> AisleB: [150] TransferLoad(load: MaterialLoad(B_5_OnRight(11)), channel: sorter_aisle_B, resource: c5)
AisleB -> AisleB_controller: [150] LoadArrival(sorter_aisle_B,MaterialLoad(B_5_OnRight(11)))
AisleB -> AisleB: [150] PulledLoad(load: MaterialLoad(B_5_OnRight(11)), channel: sorter_aisle_B, idx: 0)
AisleB_controller -> AisleB: [150] Transfer(sorter_aisle_B,shuttle_AisleB_5_in)
AisleB -> sorter: [150] AcknowledgeLoad(load: MaterialLoad(B_5_OnRight(11)), channel: sorter_aisle_B, resource: c5)
AisleB -> AisleB_carriage: [150] GoTo(Slot(OnRight(0)))
AisleB_carriage -> AisleB: [150] Arrived(GoTo(Slot(OnRight(0))))
AisleB -> AisleB_carriage: [150] Load(Slot(OnRight(0)))
AisleB_carriage -> AisleB_carriage: [158] DoneLoading(Load(Slot(OnRight(0))))
AisleB_carriage -> AisleB: [158] Loaded(Load(Slot(OnRight(0))))
AisleB -> AisleB_carriage: [158] GoTo(Slot(OnRight(5)))
sorter -> AisleB: [160] TransferLoad(load: MaterialLoad(B_5_OnRight(14)), channel: sorter_aisle_B, resource: c2)
AisleB -> AisleB_controller: [160] LoadArrival(sorter_aisle_B,MaterialLoad(B_5_OnRight(14)))
AisleB -> AisleB: [160] PulledLoad(load: MaterialLoad(B_5_OnRight(14)), channel: sorter_aisle_B, idx: 0)
AisleB -> sorter: [160] AcknowledgeLoad(load: MaterialLoad(B_5_OnRight(14)), channel: sorter_aisle_B, resource: c2)
AisleB_carriage -> AisleB_carriage: [165] Arriving(GoTo(Slot(OnRight(5))),Slot(OnRight(5)))
AisleB_carriage -> AisleB: [165] Arrived(GoTo(Slot(OnRight(5))))
AisleB -> AisleB_carriage: [165] Unload(Slot(OnRight(5)))
AisleB_carriage -> AisleB_carriage: [173] DoneUnloading(Unload(Slot(OnRight(5))))
AisleB_carriage -> AisleB: [173] Unloaded(Unload(Slot(OnRight(5))),MaterialLoad(B_5_OnRight(11)))
AisleB -> AisleB_controller: [173] CompletedCommand(Transfer(sorter_aisle_B,shuttle_AisleB_5_in))
AisleB_controller -> systemManager: [173] CompletedCommand(Transfer(sorter_aisle_B,shuttle_AisleB_5_in))
AisleB_controller -> AisleB: [173] Transfer(sorter_aisle_B,shuttle_AisleB_5_in)
AisleB -> AisleB_carriage: [173] GoTo(Slot(OnRight(0)))
AisleB -> shuttle_AisleB_5: [178] TransferLoad(load: MaterialLoad(B_5_OnRight(11)), channel: shuttle_AisleB_5_in, resource: c2)
shuttle_AisleB_5 -> shuttle_AisleB_5_controller: [178] LoadArrival(shuttle_AisleB_5_in,MaterialLoad(B_5_OnRight(11)))
shuttle_AisleB_5 -> shuttle_AisleB_5: [178] PulledLoad(load: MaterialLoad(B_5_OnRight(11)), channel: shuttle_AisleB_5_in, idx: 0)
shuttle_AisleB_5_controller -> shuttle_AisleB_5: [178] Store(shuttle_AisleB_5_in,OnRight(11))
shuttle_AisleB_5 -> AisleB: [178] AcknowledgeLoad(load: MaterialLoad(B_5_OnRight(11)), channel: shuttle_AisleB_5_in, resource: c2)
shuttle_AisleB_5 -> shuttle_AisleB_5_carriage: [178] GoTo(Slot(OnLeft(-1)))
sorter -> AisleB: [180] TransferLoad(load: MaterialLoad(B_2_OnRight(19)), channel: sorter_aisle_B, resource: c5)
AisleB_carriage -> AisleB_carriage: [180] Arriving(GoTo(Slot(OnRight(0))),Slot(OnRight(0)))
AisleB -> AisleB_controller: [180] LoadArrival(sorter_aisle_B,MaterialLoad(B_2_OnRight(19)))
AisleB_carriage -> AisleB: [180] Arrived(GoTo(Slot(OnRight(0))))
AisleB -> AisleB_carriage: [180] Load(Slot(OnRight(0)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5_carriage: [181] Arriving(GoTo(Slot(OnLeft(-1))),Slot(OnLeft(-1)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5: [181] Arrived(GoTo(Slot(OnLeft(-1))))
shuttle_AisleB_5 -> shuttle_AisleB_5_carriage: [181] Load(Slot(OnLeft(-1)))
AisleB_carriage -> AisleB_carriage: [188] DoneLoading(Load(Slot(OnRight(0))))
AisleB_carriage -> AisleB: [188] Loaded(Load(Slot(OnRight(0))))
AisleB -> AisleB_carriage: [188] GoTo(Slot(OnRight(5)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5_carriage: [189] DoneLoading(Load(Slot(OnLeft(-1))))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5: [189] Loaded(Load(Slot(OnLeft(-1))))
shuttle_AisleB_5 -> shuttle_AisleB_5_carriage: [189] GoTo(Slot(OnRight(11)))
sorter -> AisleB: [190] TransferLoad(load: MaterialLoad(B_2_OnLeft(1)), channel: sorter_aisle_B, resource: c2)
AisleB -> AisleB_controller: [190] LoadArrival(sorter_aisle_B,MaterialLoad(B_2_OnLeft(1)))
AisleB_carriage -> AisleB_carriage: [195] Arriving(GoTo(Slot(OnRight(5))),Slot(OnRight(5)))
AisleB_carriage -> AisleB: [195] Arrived(GoTo(Slot(OnRight(5))))
AisleB -> AisleB_carriage: [195] Unload(Slot(OnRight(5)))
sorter -> AisleB: [200] TransferLoad(load: MaterialLoad(B_2_OnRight(16)), channel: sorter_aisle_B, resource: c3)
shuttle_AisleB_5_carriage -> shuttle_AisleB_5_carriage: [200] Arriving(GoTo(Slot(OnRight(11))),Slot(OnRight(11)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5: [200] Arrived(GoTo(Slot(OnRight(11))))
AisleB -> AisleB_controller: [200] LoadArrival(sorter_aisle_B,MaterialLoad(B_2_OnRight(16)))
shuttle_AisleB_5 -> shuttle_AisleB_5_carriage: [200] Unload(Slot(OnRight(11)))
AisleB_carriage -> AisleB_carriage: [203] DoneUnloading(Unload(Slot(OnRight(5))))
AisleB_carriage -> AisleB: [203] Unloaded(Unload(Slot(OnRight(5))),MaterialLoad(B_5_OnRight(14)))
AisleB -> AisleB_controller: [203] CompletedCommand(Transfer(sorter_aisle_B,shuttle_AisleB_5_in))
AisleB_controller -> systemManager: [203] CompletedCommand(Transfer(sorter_aisle_B,shuttle_AisleB_5_in))
AisleB_controller -> AisleB: [203] Transfer(sorter_aisle_B,shuttle_AisleB_2_in)
AisleB -> AisleB_carriage: [203] GoTo(Slot(OnRight(0)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5_carriage: [208] DoneUnloading(Unload(Slot(OnRight(11))))
AisleB -> shuttle_AisleB_5: [208] TransferLoad(load: MaterialLoad(B_5_OnRight(14)), channel: shuttle_AisleB_5_in, resource: c2)
shuttle_AisleB_5_carriage -> shuttle_AisleB_5: [208] Unloaded(Unload(Slot(OnRight(11))),MaterialLoad(B_5_OnRight(11)))
shuttle_AisleB_5 -> shuttle_AisleB_5_controller: [208] LoadArrival(shuttle_AisleB_5_in,MaterialLoad(B_5_OnRight(14)))
shuttle_AisleB_5 -> shuttle_AisleB_5: [208] PulledLoad(load: MaterialLoad(B_5_OnRight(14)), channel: shuttle_AisleB_5_in, idx: 0)
shuttle_AisleB_5 -> shuttle_AisleB_5_controller: [208] CompletedCommand(Store(shuttle_AisleB_5_in,OnRight(11)))
shuttle_AisleB_5 -> AisleB: [208] AcknowledgeLoad(load: MaterialLoad(B_5_OnRight(14)), channel: shuttle_AisleB_5_in, resource: c2)
shuttle_AisleB_5_controller -> shuttle_AisleB_5: [208] Store(shuttle_AisleB_5_in,OnRight(14))
shuttle_AisleB_5_controller -> systemManager: [208] CompletedCommand(Store(shuttle_AisleB_5_in,OnRight(11)))
shuttle_AisleB_5 -> shuttle_AisleB_5_carriage: [208] GoTo(Slot(OnLeft(-1)))
AisleB_carriage -> AisleB_carriage: [210] Arriving(GoTo(Slot(OnRight(0))),Slot(OnRight(0)))
AisleB_carriage -> AisleB: [210] Arrived(GoTo(Slot(OnRight(0))))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5_carriage: [219] Arriving(GoTo(Slot(OnLeft(-1))),Slot(OnLeft(-1)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5: [219] Arrived(GoTo(Slot(OnLeft(-1))))
shuttle_AisleB_5 -> shuttle_AisleB_5_carriage: [219] Load(Slot(OnLeft(-1)))
sorter -> AisleB: [220] TransferLoad(load: MaterialLoad(B_2_OnRight(12)), channel: sorter_aisle_B, resource: c4)
AisleB -> AisleB_carriage: [220] Load(Slot(OnRight(0)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5_carriage: [227] DoneLoading(Load(Slot(OnLeft(-1))))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5: [227] Loaded(Load(Slot(OnLeft(-1))))
shuttle_AisleB_5 -> shuttle_AisleB_5_carriage: [227] GoTo(Slot(OnRight(14)))
AisleB_carriage -> AisleB_carriage: [228] DoneLoading(Load(Slot(OnRight(0))))
AisleB_carriage -> AisleB: [228] Loaded(Load(Slot(OnRight(0))))
AisleB -> AisleB_carriage: [228] GoTo(Slot(OnRight(2)))
sorter -> AisleB: [230] TransferLoad(load: MaterialLoad(B_5_OnRight(4)), channel: sorter_aisle_B, resource: c1)
AisleB -> AisleB_controller: [230] LoadArrival(sorter_aisle_B,MaterialLoad(B_5_OnRight(4)))
AisleB_carriage -> AisleB_carriage: [232] Arriving(GoTo(Slot(OnRight(2))),Slot(OnRight(2)))
AisleB_carriage -> AisleB: [232] Arrived(GoTo(Slot(OnRight(2))))
AisleB -> AisleB_carriage: [232] Unload(Slot(OnRight(2)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5_carriage: [240] Arriving(GoTo(Slot(OnRight(14))),Slot(OnRight(14)))
AisleB_carriage -> AisleB_carriage: [240] DoneUnloading(Unload(Slot(OnRight(2))))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5: [240] Arrived(GoTo(Slot(OnRight(14))))
AisleB_carriage -> AisleB: [240] Unloaded(Unload(Slot(OnRight(2))),MaterialLoad(B_2_OnRight(12)))
shuttle_AisleB_5 -> shuttle_AisleB_5_carriage: [240] Unload(Slot(OnRight(14)))
AisleB -> AisleB_controller: [240] CompletedCommand(Transfer(sorter_aisle_B,shuttle_AisleB_2_in))
AisleB_controller -> systemManager: [240] CompletedCommand(Transfer(sorter_aisle_B,shuttle_AisleB_2_in))
AisleB_controller -> AisleB: [240] Transfer(sorter_aisle_B,shuttle_AisleB_2_in)
AisleB -> AisleB_carriage: [240] GoTo(Slot(OnRight(0)))
AisleB_carriage -> AisleB_carriage: [244] Arriving(GoTo(Slot(OnRight(0))),Slot(OnRight(0)))
AisleB_carriage -> AisleB: [244] Arrived(GoTo(Slot(OnRight(0))))
AisleB -> shuttle_AisleB_2: [245] TransferLoad(load: MaterialLoad(B_2_OnRight(12)), channel: shuttle_AisleB_2_in, resource: c2)
shuttle_AisleB_2 -> shuttle_AisleB_2_controller: [245] LoadArrival(shuttle_AisleB_2_in,MaterialLoad(B_2_OnRight(12)))
shuttle_AisleB_2 -> shuttle_AisleB_2: [245] PulledLoad(load: MaterialLoad(B_2_OnRight(12)), channel: shuttle_AisleB_2_in, idx: 0)
shuttle_AisleB_2_controller -> shuttle_AisleB_2: [245] Store(shuttle_AisleB_2_in,OnRight(12))
shuttle_AisleB_2 -> AisleB: [245] AcknowledgeLoad(load: MaterialLoad(B_2_OnRight(12)), channel: shuttle_AisleB_2_in, resource: c2)
shuttle_AisleB_2 -> shuttle_AisleB_2_carriage: [245] GoTo(Slot(OnLeft(-1)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5_carriage: [248] DoneUnloading(Unload(Slot(OnRight(14))))
shuttle_AisleB_2_carriage -> shuttle_AisleB_2_carriage: [248] Arriving(GoTo(Slot(OnLeft(-1))),Slot(OnLeft(-1)))
shuttle_AisleB_5_carriage -> shuttle_AisleB_5: [248] Unloaded(Unload(Slot(OnRight(14))),MaterialLoad(B_5_OnRight(14)))
shuttle_AisleB_2_carriage -> shuttle_AisleB_2: [248] Arrived(GoTo(Slot(OnLeft(-1))))
shuttle_AisleB_5 -> shuttle_AisleB_5_controller: [248] CompletedCommand(Store(shuttle_AisleB_5_in,OnRight(14)))
shuttle_AisleB_2 -> shuttle_AisleB_2_carriage: [248] Load(Slot(OnLeft(-1)))
shuttle_AisleB_5_controller -> systemManager: [248] CompletedCommand(Store(shuttle_AisleB_5_in,OnRight(14)))
shuttle_AisleB_2_carriage -> shuttle_AisleB_2_carriage: [256] DoneLoading(Load(Slot(OnLeft(-1))))
shuttle_AisleB_2_carriage -> shuttle_AisleB_2: [256] Loaded(Load(Slot(OnLeft(-1))))
shuttle_AisleB_2 -> shuttle_AisleB_2_carriage: [256] GoTo(Slot(OnRight(12)))
shuttle_AisleB_2_carriage -> shuttle_AisleB_2_carriage: [268] Arriving(GoTo(Slot(OnRight(12))),Slot(OnRight(12)))
shuttle_AisleB_2_carriage -> shuttle_AisleB_2: [268] Arrived(GoTo(Slot(OnRight(12))))
shuttle_AisleB_2 -> shuttle_AisleB_2_carriage: [268] Unload(Slot(OnRight(12)))
shuttle_AisleB_2_carriage -> shuttle_AisleB_2_carriage: [276] DoneUnloading(Unload(Slot(OnRight(12))))
shuttle_AisleB_2_carriage -> shuttle_AisleB_2: [276] Unloaded(Unload(Slot(OnRight(12))),MaterialLoad(B_2_OnRight(12)))
shuttle_AisleB_2 -> shuttle_AisleB_2_controller: [276] CompletedCommand(Store(shuttle_AisleB_2_in,OnRight(12)))
shuttle_AisleB_2_controller -> systemManager: [276] CompletedCommand(Store(shuttle_AisleB_2_in,OnRight(12)))

@enduml