@startuml
actor FanInManager
boundary u1

FanInManager -> underTest: [190] Transfer(Inbound1)
underTest -> FanInManager: [0] CompletedConfiguration(Actor[akka://FanInDelayedSlotReleaseSpec/user/underTest#-1240527031])
u1 -> underTest: [12] TransferLoad(load: MaterialLoad(First Load), channel: Inbound1, resource: Ib1_c1)
underTest -> FanInManager: [12] LoadArrival(Inbound1,MaterialLoad(First Load))
underTest -> underTest: [12] PulledLoad(load: MaterialLoad(First Load), channel: Inbound1, idx: 0)
underTest -> u1: [12] AcknowledgeLoad(load: MaterialLoad(First Load), channel: Inbound1, resource: Ib1_c1)
FanInManager -> underTest: [155] Transfer(Inbound1)
underTest -> carriage: [155] GoTo(Slot(OnLeft(0)))
carriage -> carriage: [158] Arriving(GoTo(Slot(OnLeft(0))),Slot(OnLeft(0)))
carriage -> underTest: [158] Arrived(GoTo(Slot(OnLeft(0))))
underTest -> carriage: [158] Load(Slot(OnLeft(0)))
carriage -> carriage: [166] DoneLoading(Load(Slot(OnLeft(0))))
carriage -> underTest: [166] Loaded(Load(Slot(OnLeft(0))))
underTest -> carriage: [166] GoTo(Slot(OnLeft(-1)))
carriage -> carriage: [169] Arriving(GoTo(Slot(OnLeft(-1))),Slot(OnLeft(-1)))
carriage -> underTest: [169] Arrived(GoTo(Slot(OnLeft(-1))))
underTest -> carriage: [169] Unload(Slot(OnLeft(-1)))
carriage -> carriage: [177] DoneUnloading(Unload(Slot(OnLeft(-1))))
carriage -> underTest: [177] Unloaded(Unload(Slot(OnLeft(-1))),MaterialLoad(First Load))
underTest -> FanInManager: [177] CompletedCommand(Transfer(Inbound1))
underTest -> discharge: [187] TransferLoad(load: MaterialLoad(First Load), channel: Discharge, resource: Ob1_c1)
underTest -> carriage: [190] GoTo(Slot(OnLeft(0)))
carriage -> carriage: [193] Arriving(GoTo(Slot(OnLeft(0))),Slot(OnLeft(0)))
carriage -> underTest: [193] Arrived(GoTo(Slot(OnLeft(0))))
u1 -> underTest: [250] TransferLoad(load: MaterialLoad(Second Load), channel: Inbound1, resource: Ib1_c1)
underTest -> underTest: [250] PulledLoad(load: MaterialLoad(Second Load), channel: Inbound1, idx: 0)
underTest -> carriage: [250] Load(Slot(OnLeft(0)))
underTest -> u1: [250] AcknowledgeLoad(load: MaterialLoad(Second Load), channel: Inbound1, resource: Ib1_c1)
carriage -> carriage: [258] DoneLoading(Load(Slot(OnLeft(0))))
carriage -> underTest: [258] Loaded(Load(Slot(OnLeft(0))))
underTest -> carriage: [258] GoTo(Slot(OnLeft(-1)))
carriage -> carriage: [261] Arriving(GoTo(Slot(OnLeft(-1))),Slot(OnLeft(-1)))
carriage -> underTest: [261] Arrived(GoTo(Slot(OnLeft(-1))))
underTest -> carriage: [261] Unload(Slot(OnLeft(-1)))
carriage -> carriage: [269] DoneUnloading(Unload(Slot(OnLeft(-1))))
carriage -> underTest: [269] Unloaded(Unload(Slot(OnLeft(-1))),MaterialLoad(Second Load))
discharge -> discharge: [280] ConsumeLoad
discharge -> discharge: [280] PulledLoad(load: MaterialLoad(First Load), channel: Discharge, idx: 0)
discharge -> underTest: [280] AcknowledgeLoad(load: MaterialLoad(First Load), channel: Discharge, resource: Ob1_c1)
underTest -> underTest: [280] SlotBecomesAvailable(Slot(OnLeft(-1)))
underTest -> FanInManager: [280] CompletedCommand(Transfer(Inbound1))
underTest -> discharge: [290] TransferLoad(load: MaterialLoad(Second Load), channel: Discharge, resource: Ob1_c1)
discharge -> discharge: [300] ConsumeLoad
discharge -> discharge: [300] PulledLoad(load: MaterialLoad(Second Load), channel: Discharge, idx: 0)
discharge -> underTest: [300] AcknowledgeLoad(load: MaterialLoad(Second Load), channel: Discharge, resource: Ob1_c1)


@enduml