name: Scala CI

on:
  push:
    branches: [ master, saldubatech-simulation-33 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run tests
      run: sbt "coverage;test;coverageReport"
    - name: Publish tests
      run:  bash <(curl -s https://codecov.io/bash) -t 181a3344-d4e7-41d2-97cc-85443cca4e4e
